image: docker:stable

services:
- docker:dind

stages: [test]

cache:
    paths:
    - ~/.cache

variables:
    POSTGRES_DB: requestlog
    POSTGRES_USER: root
    POSTGRES_PASSWORD: "coffy"

test:
    stage: test
    services:
    - postgres:latest
    variables:
        DJANGO_SETTINGS_MODULE: sample.settings
        DB_NAME: requestlog
        DB_USER: root
        DB_PASSWORD: coffy
        DB_HOST: postgres
    script:
    - pip install -e .
    - cd __testproject
    - coverage run ./manage.py test --no-input
    - coverage report
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

