# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 22:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('requestlog', '0001_initial'), ('requestlog', '0002_auto_20180717_2228'), ('requestlog', '0003_remove_requestlog_parameters'), ('requestlog', '0004_requestlog_body'), ('requestlog', '0005_auto_20180717_2255')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
                ('url', models.TextField()),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('method', models.CharField(max_length=16)),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cookies', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('getdata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('postdata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('body', models.BinaryField(null=True)),
            ],
        ),
    ]
