# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('requestlog', '0002_requestlog_status_code'), ('requestlog', '0003_auto_20180718_0753'), ('requestlog', '0004_auto_20180718_0811')]

    dependencies = [
        ('requestlog', '0001_initial_squashed_0005_auto_20180717_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='getdata',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='postdata',
        ),
    ]
