# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestlog', '0002_requestlog_status_code_squashed_0004_auto_20180718_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_snippet',
            field=models.CharField(help_text='First 256 chars of the response.', max_length=256, null=True),
        ),
    ]
