# Generated by Django 3.2.7 on 2021-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestlog', '0004_auto_20210625_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='cookies',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='query',
            field=models.JSONField(null=True),
        ),
    ]
