# Generated by Django 4.0.3 on 2022-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestlog', '0005_auto_20211003_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='body_parsed',
            field=models.JSONField(null=True),
        ),
    ]
