name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9
    services:
      postgres:
        image: postgres
        ports:
          - 5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install -e .
    - uses: jpetrucciani/mypy-check@master
      with:
        path: 'src/'
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: sample.settings
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: postgres
      run: |
        cd __testproject
        coverage run ./manage.py test --no-input requestlog.tests
        coverage report
        coverage xml -o coverage.xml
#    - name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
